### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hoang-minhhieu** [cache117/peoplesoft-psunit#1]
Hello Cache,

First thank you for sharing this useful framework. 
I want to ask if your program supports PeopleSoft 9.2 and PTools 8.56?

Best regards,

Minh

**Comment by jsmpros** [comment]
Hi @hoang-minhhieu psunit was created a very long time ago by PeopleSoft as an internal tool. It is pretty much PeopleTools agnostic. The basic requirement is that PeopleTools support Application Classes, which has been true since 8.52.

I have used it with every PeopleTools release since 8.48.

**Comment by cache117** [comment]
@hoang-minhhieu Jim is exactly right. This was created by PeopleSoft, and will work as long as you have App Package support.

Glad it helped. This has been a useful tool for us, and I added it to Github since I couldn't find the original source anymore (as I mentioned in the README). I also added some things to it, which I thought others might benefit from.

**Comment by hoang-minhhieu** [comment]
Thanks everyone for answer my question. 
And thanks to you @cache117  for sharing such useful tool.
I wish you all a merry christmas and happy new year
